theme: jekyll-theme-cayman

title: "Code for Africa - Code of Conduct"
description: "Code for Africa's Code of Conduct across our communities online and offline."

show_downloads: "false"
google_analytics:  # TODO
